kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-cutover-service-account
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: release-cutover-sa
    namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view