apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: release-cutover-osci-config-generator
  namespace: cicd
spec:
  params:
    - name: NAME
      type: string
      default: "text"
  steps:
    - image: 'quay.io/gurnben/tekton-runner:latest'
      name: generate-osci-config
      resources: {}
      script: |
        echo "Hello World"
