apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: release-cutover-osci-config-generator-taskrun-
spec:
  serviceAccountName: release-cutover-sa
  params:
    - name: source_version
      value: "2.8"
    - name: source_pipeline_branch
      value: "2.8-integration"
    - name: dest_version
      value: "2.9"
  taskRef:
    name: release-cutover-osci-config-generator